apiVersion: hlf.kungfusoftware.es/v1alpha1
kind: FabricFollowerChannel
metadata:
  name: demo-org1msp
spec:
  
  anchorPeers:
    - host: org1-peer0.default
      port: 7051
    - host: org1-peer1.default
      port: 7051
    
  hlfIdentity:
    secretKey: user.yaml
    secretName: org1msp-admin
    secretNamespace: default

  mspId: Org1MSP
  name: demo
  externalPeersToJoin: []
  orderers:
    - certificate: |
        -----BEGIN CERTIFICATE-----
        MIIC1zCCAn6gAwIBAgIUfBmjeJvydtelyt1CJZRPG9MNP94wCgYIKoZIzj0EAwIw
        bTELMAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGlj
        YW50ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEO
        MAwGA1UEAxMFdGxzY2EwHhcNMjQwNzE3MTI0ODM1WhcNMjUwNzE4MTMwMzAwWjAk
        MRAwDgYDVQQLEwdvcmRlcmVyMRAwDgYDVQQDEwdvcmRlcmVyMFkwEwYHKoZIzj0C
        AQYIKoZIzj0DAQcDQgAE0B5TKfk3Ag5U1UZDoMfZvxu7cC/S3h5lvRLG4Gd1mD+x
        +2aGv9lcgD2AlM2Ox5bsuj7YFuc5cy7eqbEFdmK2SaOCAUMwggE/MA4GA1UdDwEB
        /wQEAwIDqDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/
        BAIwADAdBgNVHQ4EFgQUmVf5M9o+SJuovUtFdqh7j6EYGTYwKwYDVR0jBCQwIoAg
        3XALYUrXXGSUT8JEVSRKN1mlFQPj7IsHW2AQYws1u4wwVwYDVR0RBFAwToIJbG9j
        YWxob3N0gglvcmQtbm9kZTGCEW9yZC1ub2RlMS5kZWZhdWx0ghdvcmRlcmVyMC1v
        cmQubG9jYWxoby5zdIcEfwAAAYcErBIAAjBbBggqAwQFBgcIAQRPeyJhdHRycyI6
        eyJoZi5BZmZpbGlhdGlvbiI6IiIsImhmLkVucm9sbG1lbnRJRCI6Im9yZGVyZXIi
        LCJoZi5UeXBlIjoib3JkZXJlciJ9fTAKBggqhkjOPQQDAgNHADBEAiAPvNKp2STX
        GrkNH+EwXjCJloLGlFx5JLtmB8vJSUxcUgIge82+iD+3R6kUJvsZP0z/Wc1C6pRB
        1hn6OqjvInbFTiM=
        -----END CERTIFICATE-----

      url: grpcs://ord-node1.default:7050
        
  peersToJoin:
    - name: org1-peer0
      namespace: default
    - name: org1-peer1
      namespace: default
    
