---
  - block:
      - name: Setting metadata for main channel
        set_fact:
          channel_name: "jdemo"
          new_identity_key: jOrg3MSP
          peer_org_caName_to_remove: jorg3-ca
          new_identity:
            secretKey: user.yaml
            secretName: jorg3msp-admin
            secretNamespace: default
          new_peer_org:
            caName: jorg3-ca
            caNamespace: default
            mspID: jOrg3MSP
          namespace: "hlf-operator-experiment-2"

      - name: Getting orderer parameters
        shell: kubectl get fabricmainchannels.hlf.kungfusoftware.es/jdemo -o yaml | yq eval '.spec'
        register: spec

      - name: Convert spec
        set_fact:
            spec_name: "{{ spec.stdout }}"

      - name: Generate YAML file from template
        ansible.builtin.template:
            src: "templates/MainChannel/template/main_channel.yaml.j2"
            dest: "templates/MainChannel/generatedConfigs/{{ channel_name }}.yaml"

      - name: Delete entry from adminPeerOrganizations section in YAML file
        ansible.builtin.replace:
          path: templates/MainChannel/generatedConfigs/{{ channel_name }}.yaml
          regexp: '(\s*-\s*mspID:\s*{{new_identity_key}}\s*\n)'
          replace: '\n'

      - name: Delete entry from identities section in YAML file
        ansible.builtin.replace:
          path: templates/MainChannel/generatedConfigs/{{ channel_name }}.yaml
          regexp: '(\s*{{new_identity_key}}:\s*\n\s*secretKey:\s*user.yaml\s*\n\s*secretName:\s*{{new_identity_key | lower}}-admin\s*\n\s*secretNamespace:\s*{{namespace}}\s*\n)'
          replace: '\n'

      - name: Delete entries from peer section in YAML file
        ansible.builtin.replace:
          path: templates/MainChannel/generatedConfigs/{{ channel_name }}.yaml
          regexp: '(\s*-\s*caName:\s*{{peer_org_caName_to_remove}}\s*\n\s*caNamespace:\s*{{namespace}}\s*\n\s*mspID:\s*{{new_identity_key}}\s*\n)'
          replace: '\n'

      - name: Apply Main channel file 
        shell: kubectl apply -f templates/MainChannel/generatedConfigs/{{ channel_name }}.yaml