apiVersion: hlf.kungfusoftware.es/v1alpha1
kind: FabricMainChannel
metadata:
  name: demo
spec:
  name: demo
  adminOrdererOrganizations:
    - mspID: OrdererMSP
    
  adminPeerOrganizations:
    - mspID: Org1MSP
    - mspID: Org2MSP
    
  channelConfig:
    application:
      acls: null
      capabilities:
        - V2_0
      policies: null
    capabilities:
      - V2_0
    orderer:
      batchSize:
        absoluteMaxBytes: 1048576
        maxMessageCount: 10
        preferredMaxBytes: 524288
      batchTimeout: 2s
      capabilities:
        - V2_0
      etcdRaft:
        options:
          electionTick: 10
          heartbeatTick: 1
          maxInflightBlocks: 5
          snapshotIntervalSize: 16777216
          tickInterval: 500ms
      ordererType: etcdraft
      policies: null
      state: STATE_NORMAL
    policies: null
  externalOrdererOrganizations: []
  peerOrganizations:
    - mspID: Org1MSP
      caName: "org1-ca"
      caNamespace: "default"
    - mspID: Org2MSP
      caName: "org2-ca"
      caNamespace: "default"
    
  identities:
    Org1MSP:
      secretKey: user.yaml
      secretName: org1msp-admin
      secretNamespace: default
    Org2MSP:
      secretKey: user.yaml
      secretName: org2msp-admin
      secretNamespace: default
    OrdererMSP:
      secretKey: user.yaml
      secretName: orderer-orderermsp-admin-tls
      secretNamespace: default
    OrdererMSP-sign:
      secretKey: user.yaml
      secretName: orderer-orderermsp-admin-sign
      secretNamespace: default
    
  externalPeerOrganizations: []
  ordererOrganizations:
  - caName: "ord-ca"
    caNamespace: "default"
    externalOrderersToJoin:
      - host: ord-node1
        port: 7053
      
    mspID: OrdererMSP
    ordererEndpoints:
      - ord-node1:7050
      
    orderersToJoin: []
  orderers:
    - host: ord-node1
      port: 7050
      tlsCert: |-
        -----BEGIN CERTIFICATE-----
        MIIC2DCCAn6gAwIBAgIUGROGaGKuMAwWhxZ3hS5pGVpo3YQwCgYIKoZIzj0EAwIw
        bTELMAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGlj
        YW50ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEO
        MAwGA1UEAxMFdGxzY2EwHhcNMjQwNDI1MTQxNDE0WhcNMjUwNDI2MTQzNjAwWjAk
        MRAwDgYDVQQLEwdvcmRlcmVyMRAwDgYDVQQDEwdvcmRlcmVyMFkwEwYHKoZIzj0C
        AQYIKoZIzj0DAQcDQgAE2cY9eEf/SJiJXLQvoKgiRqQT0wr28hepNZGHMKGfQ+kx
        ABfTbY74DkeCRqwz7qnsjqe2iThx0KMPQQqQ1telraOCAUMwggE/MA4GA1UdDwEB
        /wQEAwIDqDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/
        BAIwADAdBgNVHQ4EFgQUpikjF9lSQxvG46cpUpiEioogntUwKwYDVR0jBCQwIoAg
        6sWnOGFkgTUfKC4a11q0TCZ56HEIkBt2spsIvWiWRrAwVwYDVR0RBFAwToIJbG9j
        YWxob3N0gglvcmQtbm9kZTGCEW9yZC1ub2RlMS5kZWZhdWx0ghdvcmRlcmVyMC1v
        cmQubG9jYWxoby5zdIcEfwAAAYcErBIAAjBbBggqAwQFBgcIAQRPeyJhdHRycyI6
        eyJoZi5BZmZpbGlhdGlvbiI6IiIsImhmLkVucm9sbG1lbnRJRCI6Im9yZGVyZXIi
        LCJoZi5UeXBlIjoib3JkZXJlciJ9fTAKBggqhkjOPQQDAgNIADBFAiEAgrZGwal9
        Ja4MwoJOV0w3fuKtmVj+L1R0diCajhDTjnkCIAGxHOJDlIx5Fp4Dk1FLRWXtojDp
        nohYm+J3Rb5dejcQ
        -----END CERTIFICATE-----

    
