apiVersion: hlf.kungfusoftware.es/v1alpha1
kind: FabricMainChannel
metadata:
  name: demo
spec:
  name: demo
  adminOrdererOrganizations:
    - mspID: OrdererMSP
    
  adminPeerOrganizations:
    - mspID: Org1MSP
    
  channelConfig:
    application:
      acls: null
      capabilities:
        - V2_0
      policies: null
    capabilities:
      - V2_0
    orderer:
      batchSize:
        absoluteMaxBytes: 1048576
        maxMessageCount: 10
        preferredMaxBytes: 524288
      batchTimeout: 2s
      capabilities:
        - V2_0
      etcdRaft:
        options:
          electionTick: 10
          heartbeatTick: 1
          maxInflightBlocks: 5
          snapshotIntervalSize: 16777216
          tickInterval: 500ms
      ordererType: etcdraft
      policies: null
      state: STATE_NORMAL
    policies: null
  externalOrdererOrganizations: []
  peerOrganizations:
    - mspID: Org1MSP
      caName: "org1-ca"
      caNamespace: "default"
    
  identities:
    Org1MSP:
      secretKey: user.yaml
      secretName: org1msp-admin
      secretNamespace: default
    OrdererMSP:
      secretKey: user.yaml
      secretName: orderer-orderermsp-admin-tls
      secretNamespace: default
    OrdererMSP-sign:
      secretKey: user.yaml
      secretName: orderer-orderermsp-admin-sign
      secretNamespace: default
    
  externalPeerOrganizations: []
  ordererOrganizations:
  - caName: "ord-ca"
    caNamespace: "default"
    externalOrderersToJoin:
      - host: ord-node1
        port: 7053
      
    mspID: OrdererMSP
    ordererEndpoints:
      - ord-node1:7050
      
    orderersToJoin: []
  orderers:
    - host: ord-node1
      port: 7050
      tlsCert: |-
        -----BEGIN CERTIFICATE-----
        MIIC1zCCAn6gAwIBAgIUfBmjeJvydtelyt1CJZRPG9MNP94wCgYIKoZIzj0EAwIw
        bTELMAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGlj
        YW50ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEO
        MAwGA1UEAxMFdGxzY2EwHhcNMjQwNzE3MTI0ODM1WhcNMjUwNzE4MTMwMzAwWjAk
        MRAwDgYDVQQLEwdvcmRlcmVyMRAwDgYDVQQDEwdvcmRlcmVyMFkwEwYHKoZIzj0C
        AQYIKoZIzj0DAQcDQgAE0B5TKfk3Ag5U1UZDoMfZvxu7cC/S3h5lvRLG4Gd1mD+x
        +2aGv9lcgD2AlM2Ox5bsuj7YFuc5cy7eqbEFdmK2SaOCAUMwggE/MA4GA1UdDwEB
        /wQEAwIDqDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/
        BAIwADAdBgNVHQ4EFgQUmVf5M9o+SJuovUtFdqh7j6EYGTYwKwYDVR0jBCQwIoAg
        3XALYUrXXGSUT8JEVSRKN1mlFQPj7IsHW2AQYws1u4wwVwYDVR0RBFAwToIJbG9j
        YWxob3N0gglvcmQtbm9kZTGCEW9yZC1ub2RlMS5kZWZhdWx0ghdvcmRlcmVyMC1v
        cmQubG9jYWxoby5zdIcEfwAAAYcErBIAAjBbBggqAwQFBgcIAQRPeyJhdHRycyI6
        eyJoZi5BZmZpbGlhdGlvbiI6IiIsImhmLkVucm9sbG1lbnRJRCI6Im9yZGVyZXIi
        LCJoZi5UeXBlIjoib3JkZXJlciJ9fTAKBggqhkjOPQQDAgNHADBEAiAPvNKp2STX
        GrkNH+EwXjCJloLGlFx5JLtmB8vJSUxcUgIge82+iD+3R6kUJvsZP0z/Wc1C6pRB
        1hn6OqjvInbFTiM=
        -----END CERTIFICATE-----

    
