apiVersion: hlf.kungfusoftware.es/v1alpha1
kind: FabricMainChannel
metadata:
  name: jdemo
spec: 
  adminOrdererOrganizations:
    - mspID: jOrdererMSP
  adminPeerOrganizations:
    - mspID: jOrg1MSP
  channelConfig:
    application:
      acls: null
      capabilities:
        - V2_0
      policies: null
    capabilities:
      - V2_0
    orderer:
      batchSize:
        absoluteMaxBytes: 1048576
        maxMessageCount: 10
        preferredMaxBytes: 524288
      batchTimeout: 2s
      capabilities:
        - V2_0
      etcdRaft:
        options:
          electionTick: 10
          heartbeatTick: 1
          maxInflightBlocks: 5
          snapshotIntervalSize: 16777216
          tickInterval: 500ms
      ordererType: etcdraft
      policies: null
      state: STATE_NORMAL
    policies: null
  externalOrdererOrganizations: []
  externalPeerOrganizations: []
  identities:
    jOrdererMSP:
      secretKey: user.yaml
      secretName: jorderer-jorderermsp-admin-tls
      secretNamespace: hlf-operator-experiment-2
    jOrdererMSP-sign:
      secretKey: user.yaml
      secretName: jorderer-jorderermsp-admin-sign
      secretNamespace: hlf-operator-experiment-2
    jOrg1MSP:
      secretKey: user.yaml
      secretName: jorg1msp-admin
      secretNamespace: hlf-operator-experiment-2
  name: jdemo
  ordererOrganizations:
    - caName: jord-ca
      caNamespace: hlf-operator-experiment-2
      externalOrderersToJoin:
        - host: jord-node1
          port: 7053
      mspID: jOrdererMSP
      ordererEndpoints:
        - jord-node1:7050
      orderersToJoin: []
  orderers:
    - host: jord-node1
      port: 7050
      tlsCert: |-
        -----BEGIN CERTIFICATE-----
        MIIDFTCCArugAwIBAgIUdSx5I0sQEIPGQwnOBoAJ1yKzDzMwCgYIKoZIzj0EAwIw
        bTELMAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGlj
        YW50ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEO
        MAwGA1UEAxMFdGxzY2EwHhcNMjQwNzE5MTQxNTIxWhcNMjUwNzIwMTQxODAwWjAk
        MRAwDgYDVQQLEwdvcmRlcmVyMRAwDgYDVQQDEwdvcmRlcmVyMFkwEwYHKoZIzj0C
        AQYIKoZIzj0DAQcDQgAEnngtHcQirfPDiNWBz8/5QZ+9tz6rKWExHyYBtrKiQsrP
        jT13rE8E3FuHBX6zDZNHxf1x7Ne4O4p+9dUq/3omrqOCAYAwggF8MA4GA1UdDwEB
        /wQEAwIDqDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/
        BAIwADAdBgNVHQ4EFgQUFXDQVMuuUO4yDP+Ilb/D+wGEccEwKwYDVR0jBCQwIoAg
        mXhEVlP0yWrwvjr2af4intq0DplZHqWXvoyG0DI0gn8wgZMGA1UdEQSBizCBiIIJ
        bG9jYWxob3N0ggpqb3JkLW5vZGUxgiRqb3JkLW5vZGUxLmhsZi1vcGVyYXRvci1l
        eHBlcmltZW50LTKCPWpvcmRlcmVyMC1vcmQuYXBwcy5saW9uc2NsdXN0ZXIxLmlu
        Zm9ybWF0aWsudW5pYnctbXVlbmNoZW4uZGWHBH8AAAGHBInBRPUwWwYIKgMEBQYH
        CAEET3siYXR0cnMiOnsiaGYuQWZmaWxpYXRpb24iOiIiLCJoZi5FbnJvbGxtZW50
        SUQiOiJvcmRlcmVyIiwiaGYuVHlwZSI6Im9yZGVyZXIifX0wCgYIKoZIzj0EAwID
        SAAwRQIhAJSbd1CMv1tr+kjeXFvn6GVp3HyUVTQHMACCglxKeOPeAiAlwQW4VWmK
        JmLDTJQI2ILIhECJ0TaIKSGLCSQhKI4UZQ==
        -----END CERTIFICATE-----
  peerOrganizations:
    - caName: jorg1-ca
      caNamespace: hlf-operator-experiment-2
      mspID: jOrg1MSP
