---
  - block:
      - name: Setting metadata for main channel
        set_fact:
          channel_name: "jdemo"
          new_identity_key: jOrg3MSP
          peer_org_caName_to_remove: jorg3-ca
          new_identity:
            secretKey: user.yaml
            secretName: org3msp-admin
            secretNamespace: hlf-operator-experiment-2
          new_peer_org:
            caName: jorg3-ca
            caNamespace: hlf-operator-experiment-2
            mspID: jOrg3MSP

      - name: Getting orderer parameters
        shell: kubectl get fabricmainchannels.hlf.kungfusoftware.es/jdemo -o yaml | yq eval '.spec'
        register: spec

      - name: Convert spec
        set_fact:
            spec_name: "{{ spec.stdout }}"

      - name: Generate YAML file from template
        ansible.builtin.template:
            src: "templates/MainChannel/template/main_channel.yaml.j2"
            dest: "templates/MainChannel/generatedConfigs/{{ channel_name }}.yaml"

    ###

      - name: Construct the new peer block
        set_fact:
            new_peer_block: |
              - caName: {{ new_peer_org.caName }}
                caNamespace: {{ new_peer_org.caNamespace }}
                mspID: {{ new_peer_org.mspID }}


      - name: Insert the new peer organization block into the YAML file
        blockinfile:
            path: templates/MainChannel/generatedConfigs/{{ channel_name }}.yaml
            insertafter: '^  peerOrganizations:'
            marker: "# {mark} ANSIBLE MANAGED BLOCK - peerOrganizations"
            block: "{{ new_peer_block | indent(4, True) }}"

      - name: Apply Main channel file 
        shell: kubectl apply -f templates/MainChannel/generatedConfigs/{{ channel_name }}.yaml