---
- name: Creating configured channels
  hosts: localhost
  vars_files:
     - config/onboarding_config.json

  tasks:
    - name: Read JSON file
      ansible.builtin.include_vars:
        file: config/onboarding_config.json
        name: onboardingconfig

    - name: Creating main channel
      include_tasks: change_main_channel.yaml

    - name: Creating follower channel
      include_tasks: create_follower_channel_config.yaml
      loop: "{{ onboardingconfig | json_query('OnboardingConfig.peerOrganisations[*]')}}"
      loop_control:
        loop_var: peer_org
        
      

    