
name: hlf-network
version: 1.0.0
client:
  organization: ""
organizations:
  
  OrdererMSP:
    mspid: OrdererMSP
    cryptoPath: /tmp/cryptopath
    users: {}
    peers: []
    orderers:
      - ord-node1.default
  Org1MSP:
    mspid: Org1MSP
    cryptoPath: /tmp/cryptopath
    users:
      org1msp-admin-default:
        cert:
          pem: |
            -----BEGIN CERTIFICATE-----
            MIICUzCCAfmgAwIBAgIUJXZeBH0adimX7nKL6e8dxcsGrSMwCgYIKoZIzj0EAwIw
            ajELMAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGlj
            YW50ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEL
            MAkGA1UEAxMCY2EwHhcNMjQwNzEyMTAxNTUyWhcNMjUwNzEzMTAyMDAwWjAgMQ4w
            DAYDVQQLEwVhZG1pbjEOMAwGA1UEAxMFYWRtaW4wWTATBgcqhkjOPQIBBggqhkjO
            PQMBBwNCAASpYQbCZ03kxRjFw+V/f7m2Oudnu19fy/YDvjFmFBmet34LEbzpZah7
            o+xctQVgfJXFhivTztbdwnhMZU4pqubWo4HGMIHDMA4GA1UdDwEB/wQEAwIHgDAM
            BgNVHRMBAf8EAjAAMB0GA1UdDgQWBBStJzmUMMDNof/I0gs6zoNCGDrxjjArBgNV
            HSMEJDAigCB39B1y7+QwsnTKyLSmTT7+KAN22b7cTN2WyLJpX1lSwjBXBggqAwQF
            BgcIAQRLeyJhdHRycyI6eyJoZi5BZmZpbGlhdGlvbiI6IiIsImhmLkVucm9sbG1l
            bnRJRCI6ImFkbWluIiwiaGYuVHlwZSI6ImFkbWluIn19MAoGCCqGSM49BAMCA0gA
            MEUCIQDPr/QX6eONiNT9Q+GX3/XxDQ0QH6PjJLws+UN1yEHmSgIgBkV4Iw4rIagn
            4TI/rrYe1C717B8mc5gm99y1YL7y7Vk=
            -----END CERTIFICATE-----
            
        key:
          pem: |
            -----BEGIN PRIVATE KEY-----
            MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgS40y88mcavdSW+CM
            25vkVONFkLiWjBIHhU2zAQE4h5WhRANCAASpYQbCZ03kxRjFw+V/f7m2Oudnu19f
            y/YDvjFmFBmet34LEbzpZah7o+xctQVgfJXFhivTztbdwnhMZU4pqubW
            -----END PRIVATE KEY-----
            
    peers:
      - org1-peer0.default
      - org1-peer1.default
    orderers: []

orderers:
  ord-node1.default:

    url: grpcs://orderer0-ord.localho.st:443


    adminUrl: https://172.18.0.2:0
    adminTlsCert: |
        -----BEGIN CERTIFICATE-----
        MIIC1zCCAn6gAwIBAgIUcNFzaI5B8dZRbYHO5Pb61eCQ6NIwCgYIKoZIzj0EAwIw
        bTELMAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGlj
        YW50ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEO
        MAwGA1UEAxMFdGxzY2EwHhcNMjQwNzEyMTAxNTU0WhcNMjUwNzEzMTAxODAwWjAk
        MRAwDgYDVQQLEwdvcmRlcmVyMRAwDgYDVQQDEwdvcmRlcmVyMFkwEwYHKoZIzj0C
        AQYIKoZIzj0DAQcDQgAELZ30oaACQDfUEpLeNIBTpm3L2AyW5BVGcFDQD1J/7gqM
        HT8KfR/s4dRbzD3F07jxpsX8Hxhp8SsyrKTFuLv6kqOCAUMwggE/MA4GA1UdDwEB
        /wQEAwIDqDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/
        BAIwADAdBgNVHQ4EFgQU/c9iWVrdrndpBnkp4SGUihRK7YkwKwYDVR0jBCQwIoAg
        APZtrlVuy8FztZkdauc7VT469uUdhu/Myz5wTq+9yz0wVwYDVR0RBFAwToIJbG9j
        YWxob3N0gglvcmQtbm9kZTGCEW9yZC1ub2RlMS5kZWZhdWx0ghdvcmRlcmVyMC1v
        cmQubG9jYWxoby5zdIcEfwAAAYcErBIAAjBbBggqAwQFBgcIAQRPeyJhdHRycyI6
        eyJoZi5BZmZpbGlhdGlvbiI6IiIsImhmLkVucm9sbG1lbnRJRCI6Im9yZGVyZXIi
        LCJoZi5UeXBlIjoib3JkZXJlciJ9fTAKBggqhkjOPQQDAgNHADBEAiBnqYO/K4XJ
        VIOStx4n7wn28CIrFy7aFebOIYi53BoC/wIgepALCjwIfuIOerkFUsD1C8uGvEAE
        pxdE04HCLWjtACo=
        -----END CERTIFICATE-----
        

    grpcOptions:
      allow-insecure: false
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRjCCAeygAwIBAgIRAKPLYVFSZ1mPBepG71cSTcYwCgYIKoZIzj0EAwIwbTEL
        MAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGljYW50
        ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEOMAwG
        A1UEAxMFdGxzY2EwHhcNMjQwNzEyMTAxNTU0WhcNMzQwNzEzMTAxNTU0WjBtMQsw
        CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
        MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
        VQQDEwV0bHNjYTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABHa57rhMXaV3Gb/f
        Se+eeD7hDoRihlU/jHEoy7/TIiAKPOFUMjuedpdrHlj2tyliUuDGMvhVED1QM2MD
        yKPjk3WjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAUBggrBgEFBQcDAgYI
        KwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQgAPZtrlVuy8FztZkd
        auc7VT469uUdhu/Myz5wTq+9yz0wCgYIKoZIzj0EAwIDSAAwRQIgRH6bWujaq68/
        +WvOqH+UNtQz1M2oyecis7dLSRo8omcCIQCspvwuM6jnCQ9o7GO4ARfLYLxeHtOt
        +yraPexIkRxb2Q==
        -----END CERTIFICATE-----
        


peers:
  org1-peer0.default:

    url: grpcs://peer0-org1.localho.st:443

    grpcOptions:
      allow-insecure: false
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRjCCAeygAwIBAgIRAPJiq7XK/JqLzNcOT/2xc6cwCgYIKoZIzj0EAwIwbTEL
        MAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGljYW50
        ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEOMAwG
        A1UEAxMFdGxzY2EwHhcNMjQwNzEyMTAxNTUyWhcNMzQwNzEzMTAxNTUyWjBtMQsw
        CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
        MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
        VQQDEwV0bHNjYTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABP+igTG+S4czn2/Y
        BSYqKBM8AEoF0W4f6qoc+WFEarpjH7/1OuYvpZnPHnijnOyVKhTIeWTnlO9pw/AT
        ElE/+GajbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAUBggrBgEFBQcDAgYI
        KwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQgoOn33oefgPxcHWkg
        gKj7MM1BHjkIS79NA5nPKi3JjFMwCgYIKoZIzj0EAwIDSAAwRQIhALQZ2/jtk0k0
        mgnv7d8iHdtb6JcH0j1VZQrDAQHGQ9GLAiBBR3vbcsP7OeUs71TjxdcCgiAungWZ
        0DOShVfWOsFebg==
        -----END CERTIFICATE-----
        
  org1-peer1.default:

    url: grpcs://peer1-org1.localho.st:443

    grpcOptions:
      allow-insecure: false
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRjCCAeygAwIBAgIRAPJiq7XK/JqLzNcOT/2xc6cwCgYIKoZIzj0EAwIwbTEL
        MAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGljYW50
        ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEOMAwG
        A1UEAxMFdGxzY2EwHhcNMjQwNzEyMTAxNTUyWhcNMzQwNzEzMTAxNTUyWjBtMQsw
        CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
        MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
        VQQDEwV0bHNjYTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABP+igTG+S4czn2/Y
        BSYqKBM8AEoF0W4f6qoc+WFEarpjH7/1OuYvpZnPHnijnOyVKhTIeWTnlO9pw/AT
        ElE/+GajbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAUBggrBgEFBQcDAgYI
        KwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQgoOn33oefgPxcHWkg
        gKj7MM1BHjkIS79NA5nPKi3JjFMwCgYIKoZIzj0EAwIDSAAwRQIhALQZ2/jtk0k0
        mgnv7d8iHdtb6JcH0j1VZQrDAQHGQ9GLAiBBR3vbcsP7OeUs71TjxdcCgiAungWZ
        0DOShVfWOsFebg==
        -----END CERTIFICATE-----
        
certificateAuthorities:
  
  ord-ca.default:

    url: https://ord-ca.localho.st:443


    registrar:
        enrollId: enroll
        enrollSecret: "enrollpw"

    caName: ca
    tlsCACerts:
      pem: 
       - |
            -----BEGIN CERTIFICATE-----
            MIICWTCCAf+gAwIBAgIRAOvuu1z5Byt2x7c4gKJY2vswCgYIKoZIzj0EAwIwUjET
            MBEGA1UEBhMKQ2FsaWZvcm5pYTEJMAcGA1UEBxMAMQkwBwYDVQQJEwAxFDASBgNV
            BAoTC0h5cGVybGVkZ2VyMQ8wDQYDVQQLEwZGYWJyaWMwHhcNMjQwNzEyMTAxNTU0
            WhcNMzQwNzEzMTAxNTU0WjBSMRMwEQYDVQQGEwpDYWxpZm9ybmlhMQkwBwYDVQQH
            EwAxCTAHBgNVBAkTADEUMBIGA1UEChMLSHlwZXJsZWRnZXIxDzANBgNVBAsTBkZh
            YnJpYzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABG9RIvyMi3tZrMFxozEgF13o
            QGWjvKbk5cMoNqj8FPLlDVl5Q0MOBC6XuTXWVRgsYvtw+Cq5JOp4mjyA6mm3KTij
            gbUwgbIwDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEF
            BQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCC93Qk2Mh38xGl1yNwVEjGv
            TL5ak4uKBRF1uI3bK2pZ3TBFBgNVHREEPjA8gglsb2NhbGhvc3SCBm9yZC1jYYIO
            b3JkLWNhLmRlZmF1bHSCEW9yZC1jYS5sb2NhbGhvLnN0hwR/AAABMAoGCCqGSM49
            BAMCA0gAMEUCIQCs/ZO/oma97Eh81Xn82+5gTOx53Z10EQJ3hvlpvCWyPwIgcDaA
            XZ9t++9eyQIW7NLo/Anzmf8KmdGguP1pQCdMPsM=
            -----END CERTIFICATE-----
            
  
  org1-ca.default:

    url: https://org1-ca.localho.st:443


    registrar:
        enrollId: enroll
        enrollSecret: "enrollpw"

    caName: ca
    tlsCACerts:
      pem: 
       - |
            -----BEGIN CERTIFICATE-----
            MIICXTCCAgKgAwIBAgIRAI0bpRF2xwllJCKBFNKFYy0wCgYIKoZIzj0EAwIwUjET
            MBEGA1UEBhMKQ2FsaWZvcm5pYTEJMAcGA1UEBxMAMQkwBwYDVQQJEwAxFDASBgNV
            BAoTC0h5cGVybGVkZ2VyMQ8wDQYDVQQLEwZGYWJyaWMwHhcNMjQwNzEyMTAxNTUy
            WhcNMzQwNzEzMTAxNTUyWjBSMRMwEQYDVQQGEwpDYWxpZm9ybmlhMQkwBwYDVQQH
            EwAxCTAHBgNVBAkTADEUMBIGA1UEChMLSHlwZXJsZWRnZXIxDzANBgNVBAsTBkZh
            YnJpYzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABHVn7vFuJavwJZge/ST47Zie
            u0oAxo9lMPldR+wti4gQT5Jq0aKt4K/8umK86NpSY3wpfGB33trI6XywSkguIpaj
            gbgwgbUwDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEF
            BQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCCoS549U8xSAh7/o0AdgleQ
            1hhwmbAvpMdxmAxTThs6jzBIBgNVHREEQTA/gglsb2NhbGhvc3SCB29yZzEtY2GC
            D29yZzEtY2EuZGVmYXVsdIISb3JnMS1jYS5sb2NhbGhvLnN0hwR/AAABMAoGCCqG
            SM49BAMCA0kAMEYCIQDrh3UG75InHseZGEMrpXlroEGUDYBU0QV7W/OHDBxk2wIh
            AK+4trlGzxOmwFTyuFVo60dW074GcqaRaiMvsjJyGNjn
            -----END CERTIFICATE-----
            
  
  org2-ca.default:

    url: https://org2-ca.localho.st:443


    registrar:
        enrollId: enroll
        enrollSecret: "enrollpw"

    caName: ca
    tlsCACerts:
      pem: 
       - |
            -----BEGIN CERTIFICATE-----
            MIICXDCCAgKgAwIBAgIRAJccADfq90fe8hS1dPRyuZ4wCgYIKoZIzj0EAwIwUjET
            MBEGA1UEBhMKQ2FsaWZvcm5pYTEJMAcGA1UEBxMAMQkwBwYDVQQJEwAxFDASBgNV
            BAoTC0h5cGVybGVkZ2VyMQ8wDQYDVQQLEwZGYWJyaWMwHhcNMjQwNzEyMTAxNTUz
            WhcNMzQwNzEzMTAxNTUzWjBSMRMwEQYDVQQGEwpDYWxpZm9ybmlhMQkwBwYDVQQH
            EwAxCTAHBgNVBAkTADEUMBIGA1UEChMLSHlwZXJsZWRnZXIxDzANBgNVBAsTBkZh
            YnJpYzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABHWnDsxlZmUdVzSN8MC4adNd
            7Xwlnp/5gd0Ke742XbOiyVo8DimMpXKzIbTX8bIklukH+shy341fLdsnY5Ln9Qyj
            gbgwgbUwDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEF
            BQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCCV6NwpTETxKXTj6lWZQ7wn
            cMLdudf9EYj/cB2rmb6SaTBIBgNVHREEQTA/gglsb2NhbGhvc3SCB29yZzItY2GC
            D29yZzItY2EuZGVmYXVsdIISb3JnMi1jYS5sb2NhbGhvLnN0hwR/AAABMAoGCCqG
            SM49BAMCA0gAMEUCIQDIYnEZr30zonz2vOjxRtx/mY1LQoAiml7aLIh0NhJqhAIg
            fL/Jt9JHAYX1vCP4Jf09wT26KepBOqGH8CoNrpjAjo8=
            -----END CERTIFICATE-----
            


channels:
  demo:

    orderers:
      - ord-node1.default

    peers:
       org1-peer0.default:
        discover: true
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
       org1-peer1.default:
        discover: true
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

