---
  - block:
      - name: Setting metadata for main channel
        set_fact:
          channel_name: "jdemo"
          org_name: "jorg3"

      - name: Getting Follower channel
        shell: kubectl get fabricfollowerchannel.hlf.kungfusoftware.es/demo-{{org_name}}msp -o yaml | yq eval '.spec'
        register: specfollower

      - name: Convert spec
        set_fact:
            specfollower_name: "{{ specfollower.stdout }}"

      - name: Generate YAML file from template
        ansible.builtin.template:
            src: "templates/FollowerChannel/template/follower_template.yaml.j2"
            dest: "templates/FollowerChannel/backup/{{ channel_name }}-{{org_name}}msp.yaml"
         
      - name: Delete follower channel
        shell: kubectl get fabricfollowerchannels.hlf.kungfusoftware.es --no-headers | grep '^{{channel_name}}-{{org_name}}' | awk '{print $1}' | xargs kubectl delete fabricfollowerchannels.hlf.kungfusoftware.es
