---
- name: Check SSRM
  hosts: localhost
  vars_files:
     - config/nodefailure_config.json

  tasks:
    - name: Read JSON file
      ansible.builtin.include_vars:
        file: config/nodefailure_config.json
        name: nodefailureconfig


    - name: Fetching connection profile of each organisation
      shell: kubectl get secret org1msp-cp -o jsonpath="{.data.config\.yaml}" | base64 --decode > certificates/org1msp-cp.yaml

    - name: execute transaction
      shell: kubectl hlf chaincode invoke --config=certificates/org1msp-cp.yaml --user=org1msp-admin-default --peer=org1-peer0.default --chaincode=token --channel=demo --fcn=init -a '[]'
      register: command_output
      ignore_errors: true
    
    - name: Check if the command failed
      debug:
        msg: "The command failed with error: {{ command_output.stderr }}"
      when: command_output.failed

    - name: Check if the command succeeded
      debug:
        msg: "The command succeeded with output: {{ command_output.stdout }}"
      when: not command_output.failed
